//! Release & channel storage (Tower 2).
//!
//! L2 **component releases** (one entity's versioned parts), L1 **vehicle
//! releases** (a tagged combination of component releases — the desired
//! whole-vehicle state), and **channel** pointers. Resolving a channel yields
//! the desired [`wire::Tree`]; the per-vehicle *campaign* to reach it is
//! generated by [`wire::flash_plan`], not stored here.
//!
//! Releases are **content-identified**: a component's identity is the hash of
//! its parts, a vehicle's identity is the hash of its member set. Creating a
//! release is therefore idempotent — the same content reuses the existing
//! release (whatever its version), so a reconcile only cuts a new version when
//! the content actually changed. The `version` is just a human label (a build
//! number); `created_at` is the build time (when this content was first cut).

use axum::extract::{Path, Query, State};
use axum::Json;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::postgres::PgRow;
use sqlx::{PgPool, Row};
use wire::{ArtifactRef, ContentHash, Entity, Part, Tree};

use crate::content::{AppError, AppState};

// --- request / response bodies ---------------------------------------------

/// `POST /admin/component-releases` body — one entity's versioned parts.
#[derive(Deserialize)]
pub struct NewComponentRelease {
    pub entity_path: String,
    pub entity_kind: String,
    pub version: String,
    pub parts: Vec<NewPart>,
}

#[derive(Deserialize)]
pub struct NewPart {
    pub id: String,
    pub kind: String,
    pub content: ContentHash,
}

/// `POST /admin/vehicle-releases` body — a tagged combination of component
/// releases (the desired whole-vehicle state).
#[derive(Deserialize)]
pub struct NewVehicleRelease {
    pub tag: String,
    pub version: String,
    pub members: Vec<i64>,
    #[serde(default)]
    pub config_snapshot: Option<Value>,
}

/// `PUT /admin/channel-targets` body — point a (channel, device, architecture)
/// at a vehicle (target) release.
#[derive(Deserialize)]
pub struct SetChannelTarget {
    pub channel: String,
    pub device: String,
    pub architecture: String,
    #[serde(alias = "target_release_id")]
    pub vehicle_release_id: i64,
}

/// Query for resolving a channel target. `device` / `architecture` are optional —
/// omit them to resolve a channel that has a single target (the common case);
/// supply both to disambiguate when a channel serves several.
#[derive(Deserialize)]
pub struct TargetSelector {
    pub channel: String,
    pub device: Option<String>,
    pub architecture: Option<String>,
}

/// A resolved release. `reused` is true when the content already had a release
/// (so the proposed version was ignored and the existing one returned).
#[derive(Serialize)]
pub struct ReleaseRef {
    pub id: i64,
    pub version: String,
    pub created_at: String,
    pub reused: bool,
}

impl ReleaseRef {
    fn from_row(row: &PgRow, reused: bool) -> Self {
        ReleaseRef {
            id: row.get("id"),
            version: row.get("version"),
            created_at: row.get("created_at"),
            reused,
        }
    }
}

/// `GET /admin/channel-targets` response — the resolved target's current vehicle
/// release (the build-number source for a reconcile) + its tree hash, or a null
/// `vehicle` if the target is unset/unknown.
#[derive(Serialize)]
pub struct ChannelTargetState {
    pub channel: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    /// Deprecated compatibility field. Prefer `target_release`.
    pub vehicle: Option<VehicleRef>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_release: Option<VehicleRef>,
    pub tree_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub config_snapshot: Option<Value>,
}

/// `PUT /admin/channel-targets` response — the resolved tuple + the tree hash
/// that binds plan -> execute.
#[derive(Serialize)]
pub struct ChannelTargetRef {
    pub channel: String,
    pub device: String,
    pub architecture: String,
    pub vehicle_release_id: i64,
    pub tree_hash: String,
}

#[derive(Clone, Serialize)]
pub struct VehicleRef {
    pub id: i64,
    pub tag: String,
    pub version: String,
    pub created_at: String,
}

// --- handlers --------------------------------------------------------------

/// `POST /admin/component-releases` — mint an L2 component release, idempotent on
/// content. Same parts as an existing release for this entity → that release is
/// returned (`reused`); otherwise a new one is cut with the proposed `version`.
pub async fn create_component_release(
    State(s): State<AppState>,
    Json(req): Json<NewComponentRelease>,
) -> Result<Json<ReleaseRef>, AppError> {
    let pool = s.pool()?;
    let identity = component_identity(&req.entity_kind, &req.parts);

    if let Some(row) = sqlx::query(
        "SELECT id, version, created_at::text AS created_at FROM component_releases \
         WHERE entity_path = $1 AND identity_hash = $2",
    )
    .bind(&req.entity_path)
    .bind(&identity)
    .fetch_optional(pool)
    .await
    .map_err(db)?
    {
        return Ok(Json(ReleaseRef::from_row(&row, true)));
    }

    let row = sqlx::query(
        "INSERT INTO component_releases (entity_path, entity_kind, version, identity_hash) \
         VALUES ($1, $2, $3, $4) RETURNING id, version, created_at::text AS created_at",
    )
    .bind(&req.entity_path)
    .bind(&req.entity_kind)
    .bind(&req.version)
    .bind(&identity)
    .fetch_one(pool)
    .await
    .map_err(db)?;
    let id: i64 = row.get("id");

    for p in &req.parts {
        sqlx::query(
            "INSERT INTO component_release_parts (release_id, part_id, part_kind, content_hash) \
             VALUES ($1, $2, $3, $4)",
        )
        .bind(id)
        .bind(&p.id)
        .bind(&p.kind)
        .bind(p.content.to_prefixed())
        .execute(pool)
        .await
        .map_err(db)?;
    }
    Ok(Json(ReleaseRef::from_row(&row, false)))
}

/// `POST /admin/vehicle-releases` — mint an L1 vehicle release (the desired
/// whole-vehicle state), idempotent on content. Same member set for this tag →
/// that release is returned (`reused`); otherwise a new one is cut.
pub async fn create_vehicle_release(
    State(s): State<AppState>,
    Json(req): Json<NewVehicleRelease>,
) -> Result<Json<ReleaseRef>, AppError> {
    let pool = s.pool()?;
    let identity = vehicle_identity(&req.members);

    if let Some(row) = sqlx::query(
        "SELECT id, version, created_at::text AS created_at FROM vehicle_releases \
         WHERE tag = $1 AND identity_hash = $2",
    )
    .bind(&req.tag)
    .bind(&identity)
    .fetch_optional(pool)
    .await
    .map_err(db)?
    {
        if req.config_snapshot.is_some() {
            sqlx::query(
                "UPDATE vehicle_releases \
                 SET config_snapshot = COALESCE(config_snapshot, $2) \
                 WHERE id = $1",
            )
            .bind(row.get::<i64, _>("id"))
            .bind(req.config_snapshot)
            .execute(pool)
            .await
            .map_err(db)?;
        }
        return Ok(Json(ReleaseRef::from_row(&row, true)));
    }

    let row = sqlx::query(
        "INSERT INTO vehicle_releases (tag, version, identity_hash, config_snapshot) \
         VALUES ($1, $2, $3, $4) RETURNING id, version, created_at::text AS created_at",
    )
    .bind(&req.tag)
    .bind(&req.version)
    .bind(&identity)
    .bind(req.config_snapshot)
    .fetch_one(pool)
    .await
    .map_err(db)?;
    let id: i64 = row.get("id");

    for m in &req.members {
        sqlx::query(
            "INSERT INTO vehicle_release_members (vehicle_release_id, component_release_id) \
             VALUES ($1, $2)",
        )
        .bind(id)
        .bind(m)
        .execute(pool)
        .await
        .map_err(db)?;
    }
    Ok(Json(ReleaseRef::from_row(&row, false)))
}

/// `PUT /admin/channel-targets` — point (channel, device, architecture) at a
/// vehicle release, and store the `tree_hash` of its resolved tree.
pub async fn set_channel_target(
    State(s): State<AppState>,
    Json(req): Json<SetChannelTarget>,
) -> Result<Json<ChannelTargetRef>, AppError> {
    let pool = s.pool()?;
    let tree = resolve_members_to_tree(pool, req.vehicle_release_id)
        .await
        .map_err(db)?;
    let th = tree_hash(&tree);
    sqlx::query(
        "INSERT INTO channel_targets \
           (channel, device, architecture, vehicle_release_id, tree_hash, updated_at) \
         VALUES ($1, $2, $3, $4, $5, now()) \
         ON CONFLICT (channel, device, architecture) \
           DO UPDATE SET vehicle_release_id = $4, tree_hash = $5, updated_at = now()",
    )
    .bind(&req.channel)
    .bind(&req.device)
    .bind(&req.architecture)
    .bind(req.vehicle_release_id)
    .bind(&th)
    .execute(pool)
    .await
    .map_err(db)?;
    Ok(Json(ChannelTargetRef {
        channel: req.channel,
        device: req.device,
        architecture: req.architecture,
        vehicle_release_id: req.vehicle_release_id,
        tree_hash: th,
    }))
}

/// `GET /admin/channels` — list channel targets and their current target releases.
pub async fn list_channels(
    State(s): State<AppState>,
) -> Result<Json<Vec<ChannelTargetState>>, AppError> {
    let pool = s.pool()?;
    let rows = sqlx::query(
        "SELECT ct.channel, ct.device, ct.architecture, ct.tree_hash, \
                v.config_snapshot, v.id, v.tag, v.version, \
                v.created_at::text AS created_at \
         FROM channel_targets ct JOIN vehicle_releases v ON v.id = ct.vehicle_release_id \
         ORDER BY ct.channel, ct.device, ct.architecture",
    )
    .fetch_all(pool)
    .await
    .map_err(db)?;

    let targets = rows
        .into_iter()
        .map(|r| {
            let target_release = VehicleRef {
                id: r.get("id"),
                tag: r.get("tag"),
                version: r.get("version"),
                created_at: r.get("created_at"),
            };
            ChannelTargetState {
                channel: r.get("channel"),
                device: Some(r.get("device")),
                architecture: Some(r.get("architecture")),
                vehicle: Some(target_release.clone()),
                target_release: Some(target_release),
                tree_hash: Some(r.get("tree_hash")),
                config_snapshot: r.get("config_snapshot"),
            }
        })
        .collect();

    Ok(Json(targets))
}

/// `GET /admin/channel-targets?channel=&target_type=&profile=` — the resolved
/// target's current vehicle release (the build-number source for a reconcile) +
/// its tree hash. `target_type`/`profile` are optional (default: the channel's
/// single target). A null `vehicle` means the target is unset/unknown.
pub async fn get_channel_target(
    State(s): State<AppState>,
    Query(sel): Query<TargetSelector>,
) -> Result<Json<ChannelTargetState>, AppError> {
    let pool = s.pool()?;
    let row = sqlx::query(
        "SELECT ct.device, ct.architecture, v.config_snapshot, v.id, v.tag, v.version, \
                v.created_at::text AS created_at, ct.tree_hash \
         FROM channel_targets ct JOIN vehicle_releases v ON v.id = ct.vehicle_release_id \
         WHERE ct.channel = $1 \
           AND ($2::text IS NULL OR ct.device = $2) \
           AND ($3::text IS NULL OR ct.architecture = $3) \
         ORDER BY ct.updated_at DESC LIMIT 1",
    )
    .bind(&sel.channel)
    .bind(&sel.device)
    .bind(&sel.architecture)
    .fetch_optional(pool)
    .await
    .map_err(db)?;

    let (device, architecture, target_release, tree_hash, config_snapshot) = match row {
        Some(r) => (
            Some(r.get("device")),
            Some(r.get("architecture")),
            Some(VehicleRef {
                id: r.get("id"),
                tag: r.get("tag"),
                version: r.get("version"),
                created_at: r.get("created_at"),
            }),
            Some(r.get::<String, _>("tree_hash")),
            r.get("config_snapshot"),
        ),
        None => (None, None, None, None, None),
    };
    Ok(Json(ChannelTargetState {
        channel: sel.channel,
        device,
        architecture,
        vehicle: target_release.clone(),
        target_release,
        tree_hash,
        config_snapshot,
    }))
}

/// `GET /channel-targets/tree?channel=&target_type=&profile=` — resolve a target
/// to its desired tree. `target_type`/`profile` optional (default: the channel's
/// single target).
pub async fn channel_target_tree(
    State(s): State<AppState>,
    Query(sel): Query<TargetSelector>,
) -> Result<Json<Tree>, AppError> {
    let tree = resolve_channel_target(
        s.pool()?,
        &sel.channel,
        sel.device.as_deref(),
        sel.architecture.as_deref(),
    )
    .await
    .map_err(db)?
    .ok_or(AppError::NotFound)?;
    Ok(Json(tree))
}

/// `GET /admin/artifacts/{inner}` — does Tower 2 already have this content?
/// `200` + the ref if stored, `404` if not — so a build step can skip the upload.
pub async fn artifact_exists(
    State(s): State<AppState>,
    Path(inner): Path<String>,
) -> Result<Json<ArtifactRef>, AppError> {
    let inner: ContentHash = inner.parse().map_err(|_| AppError::BadHash)?;
    match s.index.get(&inner).await? {
        Some(e) => Ok(Json(ArtifactRef {
            inner: e.inner,
            outer: e.outer,
            size: e.size,
        })),
        None => Err(AppError::NotFound),
    }
}

// --- identity --------------------------------------------------------------

/// A component release's content identity: a hash over its entity kind and its
/// parts (sorted by id, so order doesn't matter). Two releases with the same
/// identity have byte-identical content.
fn component_identity(entity_kind: &str, parts: &[NewPart]) -> String {
    let mut sorted: Vec<&NewPart> = parts.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));

    let mut buf = String::new();
    buf.push_str(entity_kind);
    buf.push('\n');
    for p in sorted {
        buf.push_str(&p.id);
        buf.push('\0');
        buf.push_str(&p.kind);
        buf.push('\0');
        buf.push_str(&p.content.to_prefixed());
        buf.push('\n');
    }
    ContentHash::of(buf.as_bytes()).to_prefixed()
}

/// A vehicle release's content identity: a hash over its (sorted, deduped)
/// member component-release ids. Member ids are themselves content-deduped, so
/// the same whole-vehicle content yields the same identity.
fn vehicle_identity(members: &[i64]) -> String {
    let mut sorted = members.to_vec();
    sorted.sort_unstable();
    sorted.dedup();
    let joined = sorted
        .iter()
        .map(|m| m.to_string())
        .collect::<Vec<_>>()
        .join(",");
    ContentHash::of(joined.as_bytes()).to_prefixed()
}

// --- resolution ------------------------------------------------------------

/// Resolve a (channel, device?, architecture?) to its desired [`wire::Tree`].
/// `None` when the target is unknown (or, without an explicit device/arch, the
/// channel has zero or several targets — the caller then asks for a selector).
async fn resolve_channel_target(
    pool: &PgPool,
    channel: &str,
    device: Option<&str>,
    architecture: Option<&str>,
) -> sqlx::Result<Option<Tree>> {
    let Some(vehicle_id) = channel_target_vehicle(pool, channel, device, architecture).await?
    else {
        return Ok(None);
    };
    Ok(Some(resolve_members_to_tree(pool, vehicle_id).await?))
}

/// The vehicle release id a (channel, device?, architecture?) points at. With an
/// explicit device+architecture it's an exact lookup; without, it resolves a
/// channel that has exactly one target (zero or many -> `None`).
async fn channel_target_vehicle(
    pool: &PgPool,
    channel: &str,
    device: Option<&str>,
    architecture: Option<&str>,
) -> sqlx::Result<Option<i64>> {
    if let (Some(d), Some(a)) = (device, architecture) {
        let row = sqlx::query(
            "SELECT vehicle_release_id FROM channel_targets \
             WHERE channel = $1 AND device = $2 AND architecture = $3",
        )
        .bind(channel)
        .bind(d)
        .bind(a)
        .fetch_optional(pool)
        .await?;
        return Ok(row.map(|r| r.get("vehicle_release_id")));
    }
    let rows = sqlx::query("SELECT vehicle_release_id FROM channel_targets WHERE channel = $1")
        .bind(channel)
        .fetch_all(pool)
        .await?;
    Ok(if rows.len() == 1 {
        Some(rows[0].get("vehicle_release_id"))
    } else {
        None
    })
}

/// A vehicle release id -> its desired [`wire::Tree`] (member component releases
/// -> their entities + parts).
async fn resolve_members_to_tree(pool: &PgPool, vehicle_id: i64) -> sqlx::Result<Tree> {
    let members = sqlx::query(
        "SELECT component_release_id FROM vehicle_release_members WHERE vehicle_release_id = $1",
    )
    .bind(vehicle_id)
    .fetch_all(pool)
    .await?;

    let mut tree = Tree::default();
    for m in members {
        let rid: i64 = m.get("component_release_id");
        let row = sqlx::query(
            "SELECT entity_path, entity_kind, version FROM component_releases WHERE id = $1",
        )
        .bind(rid)
        .fetch_one(pool)
        .await?;
        let path: String = row.get("entity_path");
        let mut entity = Entity {
            kind: row.get("entity_kind"),
            version: Some(row.get("version")),
            update_mode: None,
            parts: Vec::new(),
        };
        let parts =
            sqlx::query("SELECT part_id, part_kind, content_hash FROM component_release_parts WHERE release_id = $1")
                .bind(rid)
                .fetch_all(pool)
                .await?;
        for p in parts {
            let content: String = p.get("content_hash");
            let Ok(content) = content.parse::<ContentHash>() else {
                continue;
            };
            entity.parts.push(Part {
                kind: p.get("part_kind"),
                id: p.get("part_id"),
                content,
            });
        }
        tree.entities.insert(path, entity);
    }
    Ok(tree)
}

/// Content-stable canonical hash of a resolved tree: entity paths in order (the
/// [`Tree`] map is already sorted), each with its parts sorted by id. Binds
/// plan -> execute (multi-profile spec §2.2) — unlike a vehicle release's
/// id-based identity hash, it is identical across DB instances for the same
/// content.
fn tree_hash(tree: &Tree) -> String {
    let mut buf = String::new();
    for (path, entity) in &tree.entities {
        buf.push_str(path);
        buf.push('\n');
        let mut parts: Vec<&Part> = entity.parts.iter().collect();
        parts.sort_by(|a, b| a.id.cmp(&b.id));
        for p in parts {
            buf.push_str(&p.id);
            buf.push('\0');
            buf.push_str(&p.content.to_prefixed());
            buf.push('\n');
        }
    }
    ContentHash::of(buf.as_bytes()).to_prefixed()
}

/// Map a database error into an `AppError`.
fn db(e: sqlx::Error) -> AppError {
    AppError::Internal(e.into())
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use axum::routing::{get, post, put};
    use axum::Router;
    use tower::ServiceExt;

    use crate::content::AppState;
    use crate::signer::Signer;
    use crate::store::{FsBlobStore, PgIndex};

    fn part(id: &str, kind: &str, content: &str) -> NewPart {
        NewPart {
            id: id.into(),
            kind: kind.into(),
            content: ContentHash::of(content.as_bytes()),
        }
    }

    #[test]
    fn component_identity_ignores_part_order() {
        let a = vec![part("kernel", "bank", "k"), part("rootfs", "bank", "r")];
        let b = vec![part("rootfs", "bank", "r"), part("kernel", "bank", "k")];
        assert_eq!(
            component_identity("bank", &a),
            component_identity("bank", &b)
        );
    }

    #[test]
    fn component_identity_tracks_content_kind_and_partset() {
        let base = vec![part("kernel", "bank", "k1")];
        // content change
        assert_ne!(
            component_identity("bank", &base),
            component_identity("bank", &[part("kernel", "bank", "k2")])
        );
        // added part
        assert_ne!(
            component_identity("bank", &base),
            component_identity(
                "bank",
                &[part("kernel", "bank", "k1"), part("rootfs", "bank", "r")]
            )
        );
        // entity kind change
        assert_ne!(
            component_identity("bank", &base),
            component_identity("rt", &base)
        );
    }

    #[test]
    fn set_channel_target_accepts_target_release_alias() {
        let req: SetChannelTarget = serde_json::from_value(serde_json::json!({
            "channel": "bleeding",
            "device": "rig",
            "architecture": "arm64",
            "target_release_id": 42
        }))
        .unwrap();

        assert_eq!(req.channel, "bleeding");
        assert_eq!(req.device, "rig");
        assert_eq!(req.architecture, "arm64");
        assert_eq!(req.vehicle_release_id, 42);
    }

    #[test]
    fn new_vehicle_release_accepts_optional_config_snapshot() {
        let req: NewVehicleRelease = serde_json::from_value(serde_json::json!({
            "tag": "managed-cvc-rig",
            "version": "1.0.0-dev.1",
            "members": [1, 2],
            "config_snapshot": {
                "schema": "sumo-target-config/v1",
                "deployment": {"channel": "bleeding", "profile": "default"}
            }
        }))
        .unwrap();

        assert_eq!(req.tag, "managed-cvc-rig");
        assert_eq!(
            req.config_snapshot.unwrap()["schema"],
            "sumo-target-config/v1"
        );
    }

    #[ignore = "requires a PostgreSQL DATABASE_URL for sqlx::test"]
    #[sqlx::test(migrations = "./migrations")]
    async fn vehicle_release_snapshot_survives_reuse_and_channel_reads(pool: PgPool) {
        let app = test_app(pool);
        let component_id = create_component(&app).await;
        let original_snapshot = serde_json::json!({
            "schema": "sumo-target-config/v1",
            "target_type": {"name": "managed-cvc", "kind": "vehicle"},
            "deployment": {"channel": "bleeding", "profile": "default"},
            "labels": {"tower": "2"},
            "components": {
                "ecu-a": {
                    "kind": "adaptive-app",
                    "version": "1.0.0",
                    "parts": [{"id": "app", "kind": "binary", "source": "app.bin"}]
                }
            }
        });
        let replacement_snapshot = serde_json::json!({
            "schema": "sumo-target-config/v1",
            "deployment": {"channel": "bleeding", "profile": "replacement"}
        });

        let release = post_json(
            &app,
            "/admin/vehicle-releases",
            serde_json::json!({
                "tag": "managed-cvc",
                "version": "1.0.0",
                "members": [component_id],
                "config_snapshot": original_snapshot,
            }),
        )
        .await;
        assert_eq!(release["reused"], false);
        let release_id = release["id"].as_i64().unwrap();

        put_json(
            &app,
            "/admin/channel-targets",
            serde_json::json!({
                "channel": "bleeding",
                "device": "rig",
                "architecture": "arm64",
                "target_release_id": release_id
            }),
        )
        .await;

        let reused = post_json(
            &app,
            "/admin/vehicle-releases",
            serde_json::json!({
                "tag": "managed-cvc",
                "version": "2.0.0",
                "members": [component_id],
                "config_snapshot": replacement_snapshot,
            }),
        )
        .await;
        assert_eq!(reused["id"], release_id);
        assert_eq!(reused["reused"], true);

        let channel = get_json(
            &app,
            "/admin/channel-targets?channel=bleeding&device=rig&architecture=arm64",
        )
        .await;
        assert_eq!(channel["target_release"]["id"], release_id);
        assert_eq!(
            channel["config_snapshot"]["deployment"]["profile"],
            "default"
        );
        assert_eq!(channel["config_snapshot"]["labels"]["tower"], "2");

        let channels = get_json(&app, "/admin/channels").await;
        assert_eq!(channels[0]["channel"], "bleeding");
        assert_eq!(channels[0]["device"], "rig");
        assert_eq!(channels[0]["architecture"], "arm64");
        assert_eq!(channels[0]["target_release"]["id"], release_id);
        assert_eq!(
            channels[0]["config_snapshot"]["deployment"]["profile"],
            "default"
        );
    }

    #[test]
    fn vehicle_identity_ignores_order_and_dupes() {
        assert_eq!(vehicle_identity(&[1, 2, 3]), vehicle_identity(&[3, 2, 1]));
        assert_eq!(
            vehicle_identity(&[1, 2, 2, 3]),
            vehicle_identity(&[1, 2, 3])
        );
        assert_ne!(vehicle_identity(&[1, 2]), vehicle_identity(&[1, 2, 3]));
    }

    fn test_app(pool: PgPool) -> Router {
        let blob_dir = tempfile::tempdir().unwrap().keep();
        let signer = Signer::generate().unwrap();
        let state = AppState {
            blobs: Arc::new(FsBlobStore::new(blob_dir)),
            index: Arc::new(PgIndex::new(pool.clone())),
            pool: Some(pool),
            signer: Arc::new(signer),
        };

        Router::new()
            .route("/admin/component-releases", post(create_component_release))
            .route("/admin/vehicle-releases", post(create_vehicle_release))
            .route("/admin/channels", get(list_channels))
            .route(
                "/admin/channel-targets",
                put(set_channel_target).get(get_channel_target),
            )
            .with_state(state)
    }

    async fn create_component(app: &Router) -> i64 {
        let response = post_json(
            app,
            "/admin/component-releases",
            serde_json::json!({
                "entity_path": "ecu-a",
                "entity_kind": "adaptive-app",
                "version": "1.0.0",
                "parts": [{
                    "id": "app",
                    "kind": "binary",
                    "content": ContentHash::of(b"app").to_prefixed(),
                }],
            }),
        )
        .await;
        response["id"].as_i64().unwrap()
    }

    async fn get_json(app: &Router, uri: &str) -> Value {
        let response = app
            .clone()
            .oneshot(Request::get(uri).body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        serde_json::from_slice(&bytes).unwrap()
    }

    async fn post_json(app: &Router, uri: &str, body: Value) -> Value {
        json_request(app, Request::post(uri), body, StatusCode::OK).await
    }

    async fn put_json(app: &Router, uri: &str, body: Value) -> Value {
        json_request(app, Request::put(uri), body, StatusCode::OK).await
    }

    async fn json_request(
        app: &Router,
        builder: axum::http::request::Builder,
        body: Value,
        status: StatusCode,
    ) -> Value {
        let response = app
            .clone()
            .oneshot(
                builder
                    .header("content-type", "application/json")
                    .body(Body::from(body.to_string()))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), status);
        let bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap()
        }
    }
}
