//! Release & channel storage (Tower 2).
//!
//! L2 **component releases** (one entity's versioned parts), L1 **vehicle
//! releases** (a tagged combination of component releases — the desired
//! whole-vehicle state), and **channel** pointers. Resolving a channel yields
//! the desired [`wire::Tree`]; the per-vehicle *campaign* to reach it is
//! generated by [`wire::flash_plan`], not stored here.
//!
//! Releases are **content-identified**: a component's identity is the hash of
//! its parts, a vehicle's identity is the hash of its member set. Creating a
//! release is therefore idempotent — the same content reuses the existing
//! release (whatever its version), so a reconcile only cuts a new version when
//! the content actually changed. The `version` is just a human label (a build
//! number); `created_at` is the build time (when this content was first cut).

use axum::extract::{Path, Query, State};
use axum::http::{header, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::postgres::PgRow;
use sqlx::{PgPool, Row};
use sumo_offboard::cose_key::CoseKey;
use wire::{ArtifactRef, ContentHash, Entity, Part, Tree};

use crate::content::{AppError, AppState};
use crate::signer::EnvelopePart;

// --- request / response bodies ---------------------------------------------

/// `POST /admin/component-releases` body — one entity's versioned parts.
#[derive(Deserialize)]
pub struct NewComponentRelease {
    pub entity_path: String,
    pub entity_kind: String,
    pub version: String,
    pub parts: Vec<NewPart>,
}

#[derive(Deserialize)]
pub struct NewPart {
    pub id: String,
    pub kind: String,
    pub content: ContentHash,
}

/// `POST /admin/vehicle-releases` body — a tagged combination of component
/// releases (the desired whole-vehicle state).
#[derive(Deserialize)]
pub struct NewVehicleRelease {
    pub tag: String,
    pub version: String,
    pub members: Vec<i64>,
    /// Member ids (a subset of `members`) to mark **disabled** — deactivated in
    /// this release rather than flashed. Additive: absent ⇒ every member enabled
    /// (the pre-disable behavior). Ids not in `members` have no effect.
    #[serde(default)]
    pub disabled_members: Vec<i64>,
    #[serde(default)]
    pub config_snapshot: Option<Value>,
}

/// `PUT /admin/channel-targets` body — point a (channel, device, architecture)
/// at a vehicle (target) release.
#[derive(Deserialize)]
pub struct SetChannelTarget {
    pub channel: String,
    pub device: String,
    pub architecture: String,
    #[serde(alias = "target_release_id")]
    pub vehicle_release_id: i64,
}

/// Query for resolving a channel target. `device` / `architecture` are optional —
/// omit them to resolve a channel that has a single target (the common case);
/// supply both to disambiguate when a channel serves several.
#[derive(Deserialize)]
pub struct TargetSelector {
    pub channel: Option<String>,
    pub device: Option<String>,
    pub architecture: Option<String>,
    pub vehicle_release_id: Option<i64>,
    pub tree_hash: Option<String>,
}

/// A resolved release. `reused` is true when the content already had a release
/// (so the proposed version was ignored and the existing one returned).
#[derive(Serialize)]
pub struct ReleaseRef {
    pub id: i64,
    pub version: String,
    pub created_at: String,
    pub reused: bool,
}

impl ReleaseRef {
    fn from_row(row: &PgRow, reused: bool) -> Self {
        ReleaseRef {
            id: row.get("id"),
            version: row.get("version"),
            created_at: row.get("created_at"),
            reused,
        }
    }
}

/// `GET /admin/channel-targets` response — the resolved target's current vehicle
/// release (the build-number source for a reconcile) + its tree hash, or a null
/// `vehicle` if the target is unset/unknown.
#[derive(Serialize)]
pub struct ChannelTargetState {
    pub channel: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    /// Deprecated compatibility field. Prefer `target_release`.
    pub vehicle: Option<VehicleRef>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_release: Option<VehicleRef>,
    pub tree_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub config_snapshot: Option<Value>,
}

/// `PUT /admin/channel-targets` response — the resolved tuple + the tree hash
/// that binds plan -> execute.
#[derive(Serialize)]
pub struct ChannelTargetRef {
    pub channel: String,
    pub device: String,
    pub architecture: String,
    pub vehicle_release_id: i64,
    pub tree_hash: String,
}

#[derive(Clone, Serialize)]
pub struct VehicleRef {
    pub id: i64,
    pub tag: String,
    pub version: String,
    pub created_at: String,
}

/// Query for the release-history lists — an optional filter on the release's
/// stable key (`entity_path` for components, `tag` for vehicles). Omit to list
/// the whole history across all entities/tags.
#[derive(Deserialize)]
pub struct HistoryFilter {
    pub entity_path: Option<String>,
    pub tag: Option<String>,
}

/// `GET /admin/component-releases` row — one historical L2 component release with
/// its content parts. History is inherent: content-identity means each distinct
/// content is its own timestamped, revert-safe row.
#[derive(Serialize)]
pub struct ComponentReleaseRow {
    pub id: i64,
    pub entity_path: String,
    pub entity_kind: String,
    pub version: String,
    pub identity_hash: Option<String>,
    pub created_at: String,
    pub parts: Vec<PartRow>,
}

#[derive(Serialize)]
pub struct PartRow {
    pub id: String,
    pub kind: String,
    pub content_hash: String,
}

/// `GET /admin/vehicle-releases` row — one historical L1 vehicle release with the
/// ids of its member component releases.
#[derive(Serialize)]
pub struct VehicleReleaseRow {
    pub id: i64,
    pub tag: String,
    pub version: String,
    pub identity_hash: Option<String>,
    pub created_at: String,
    pub members: Vec<i64>,
}

// --- handlers --------------------------------------------------------------

/// `POST /admin/component-releases` — mint an L2 component release, idempotent on
/// content. Same parts as an existing release for this entity → that release is
/// returned (`reused`); otherwise a new one is cut with the proposed `version`.
pub async fn create_component_release(
    State(s): State<AppState>,
    Json(req): Json<NewComponentRelease>,
) -> Result<Json<ReleaseRef>, AppError> {
    let pool = s.pool()?;
    let identity = component_identity(&req.entity_kind, &req.parts);

    if let Some(row) = sqlx::query(
        "SELECT id, version, created_at::text AS created_at FROM component_releases \
         WHERE entity_path = $1 AND identity_hash = $2",
    )
    .bind(&req.entity_path)
    .bind(&identity)
    .fetch_optional(pool)
    .await
    .map_err(db)?
    {
        return Ok(Json(ReleaseRef::from_row(&row, true)));
    }

    let row = sqlx::query(
        "INSERT INTO component_releases (entity_path, entity_kind, version, identity_hash) \
         VALUES ($1, $2, $3, $4) RETURNING id, version, created_at::text AS created_at",
    )
    .bind(&req.entity_path)
    .bind(&req.entity_kind)
    .bind(&req.version)
    .bind(&identity)
    .fetch_one(pool)
    .await
    .map_err(db)?;
    let id: i64 = row.get("id");

    for p in &req.parts {
        sqlx::query(
            "INSERT INTO component_release_parts (release_id, part_id, part_kind, content_hash) \
             VALUES ($1, $2, $3, $4)",
        )
        .bind(id)
        .bind(&p.id)
        .bind(&p.kind)
        .bind(p.content.to_prefixed())
        .execute(pool)
        .await
        .map_err(db)?;
    }
    Ok(Json(ReleaseRef::from_row(&row, false)))
}

/// `POST /admin/vehicle-releases` — mint an L1 vehicle release (the desired
/// whole-vehicle state), idempotent on content. Same member set for this tag →
/// that release is returned (`reused`); otherwise a new one is cut.
pub async fn create_vehicle_release(
    State(s): State<AppState>,
    Json(req): Json<NewVehicleRelease>,
) -> Result<Json<ReleaseRef>, AppError> {
    let pool = s.pool()?;
    let identity = vehicle_identity(&req.members, &req.disabled_members);

    if let Some(row) = sqlx::query(
        "SELECT id, version, created_at::text AS created_at FROM vehicle_releases \
         WHERE tag = $1 AND identity_hash = $2",
    )
    .bind(&req.tag)
    .bind(&identity)
    .fetch_optional(pool)
    .await
    .map_err(db)?
    {
        if req.config_snapshot.is_some() {
            sqlx::query(
                "UPDATE vehicle_releases \
                 SET config_snapshot = COALESCE(config_snapshot, $2) \
                 WHERE id = $1",
            )
            .bind(row.get::<i64, _>("id"))
            .bind(req.config_snapshot)
            .execute(pool)
            .await
            .map_err(db)?;
        }
        return Ok(Json(ReleaseRef::from_row(&row, true)));
    }

    let row = sqlx::query(
        "INSERT INTO vehicle_releases (tag, version, identity_hash, config_snapshot) \
         VALUES ($1, $2, $3, $4) RETURNING id, version, created_at::text AS created_at",
    )
    .bind(&req.tag)
    .bind(&req.version)
    .bind(&identity)
    .bind(req.config_snapshot)
    .fetch_one(pool)
    .await
    .map_err(db)?;
    let id: i64 = row.get("id");

    for m in &req.members {
        sqlx::query(
            "INSERT INTO vehicle_release_members (vehicle_release_id, component_release_id, disabled) \
             VALUES ($1, $2, $3)",
        )
        .bind(id)
        .bind(m)
        .bind(req.disabled_members.contains(m))
        .execute(pool)
        .await
        .map_err(db)?;
    }
    Ok(Json(ReleaseRef::from_row(&row, false)))
}

/// `GET /admin/component-releases[?entity_path=]` — the L2 release history,
/// newest first, each with its content parts. Content-identity makes this a true
/// timeline: every distinct content is its own row, and a revert re-selects the
/// existing row rather than cutting a duplicate.
pub async fn list_component_releases(
    State(s): State<AppState>,
    Query(f): Query<HistoryFilter>,
) -> Result<Json<Vec<ComponentReleaseRow>>, AppError> {
    let pool = s.pool()?;
    let rows = sqlx::query(
        "SELECT id, entity_path, entity_kind, version, identity_hash, \
                created_at::text AS created_at \
         FROM component_releases \
         WHERE ($1::text IS NULL OR entity_path = $1) \
         ORDER BY created_at DESC, id DESC",
    )
    .bind(&f.entity_path)
    .fetch_all(pool)
    .await
    .map_err(db)?;

    let mut out = Vec::with_capacity(rows.len());
    for r in &rows {
        let id: i64 = r.get("id");
        let part_rows = sqlx::query(
            "SELECT part_id, part_kind, content_hash FROM component_release_parts \
             WHERE release_id = $1 ORDER BY part_id",
        )
        .bind(id)
        .fetch_all(pool)
        .await
        .map_err(db)?;
        out.push(ComponentReleaseRow {
            id,
            entity_path: r.get("entity_path"),
            entity_kind: r.get("entity_kind"),
            version: r.get("version"),
            identity_hash: r.get("identity_hash"),
            created_at: r.get("created_at"),
            parts: part_rows
                .into_iter()
                .map(|p| PartRow {
                    id: p.get("part_id"),
                    kind: p.get("part_kind"),
                    content_hash: p.get("content_hash"),
                })
                .collect(),
        });
    }
    Ok(Json(out))
}

/// `GET /admin/vehicle-releases[?tag=]` — the L1 release history, newest first,
/// each with the ids of its member component releases.
pub async fn list_vehicle_releases(
    State(s): State<AppState>,
    Query(f): Query<HistoryFilter>,
) -> Result<Json<Vec<VehicleReleaseRow>>, AppError> {
    let pool = s.pool()?;
    let rows = sqlx::query(
        "SELECT id, tag, version, identity_hash, created_at::text AS created_at \
         FROM vehicle_releases \
         WHERE ($1::text IS NULL OR tag = $1) \
         ORDER BY created_at DESC, id DESC",
    )
    .bind(&f.tag)
    .fetch_all(pool)
    .await
    .map_err(db)?;

    let mut out = Vec::with_capacity(rows.len());
    for r in &rows {
        let id: i64 = r.get("id");
        let member_rows = sqlx::query(
            "SELECT component_release_id FROM vehicle_release_members \
             WHERE vehicle_release_id = $1 ORDER BY component_release_id",
        )
        .bind(id)
        .fetch_all(pool)
        .await
        .map_err(db)?;
        out.push(VehicleReleaseRow {
            id,
            tag: r.get("tag"),
            version: r.get("version"),
            identity_hash: r.get("identity_hash"),
            created_at: r.get("created_at"),
            members: member_rows
                .into_iter()
                .map(|m| m.get::<i64, _>("component_release_id"))
                .collect(),
        });
    }
    Ok(Json(out))
}

/// `PUT /admin/channel-targets` — point (channel, device, architecture) at a
/// vehicle release, and store the `tree_hash` of its resolved tree.
pub async fn set_channel_target(
    State(s): State<AppState>,
    Json(req): Json<SetChannelTarget>,
) -> Result<Json<ChannelTargetRef>, AppError> {
    let pool = s.pool()?;
    let tree = resolve_members_to_tree(pool, req.vehicle_release_id)
        .await
        .map_err(db)?;
    let th = tree_hash(&tree);
    let mut tx = pool.begin().await.map_err(db)?;
    sqlx::query(
        "INSERT INTO vehicle_release_targets (vehicle_release_id, device, architecture) \
         VALUES ($1, $2, $3) ON CONFLICT DO NOTHING",
    )
    .bind(req.vehicle_release_id)
    .bind(&req.device)
    .bind(&req.architecture)
    .execute(&mut *tx)
    .await
    .map_err(db)?;
    sqlx::query(
        "INSERT INTO channel_targets \
           (channel, device, architecture, vehicle_release_id, tree_hash, updated_at) \
         VALUES ($1, $2, $3, $4, $5, now()) \
         ON CONFLICT (channel, device, architecture) \
           DO UPDATE SET vehicle_release_id = $4, tree_hash = $5, updated_at = now()",
    )
    .bind(&req.channel)
    .bind(&req.device)
    .bind(&req.architecture)
    .bind(req.vehicle_release_id)
    .bind(&th)
    .execute(&mut *tx)
    .await
    .map_err(db)?;
    tx.commit().await.map_err(db)?;
    Ok(Json(ChannelTargetRef {
        channel: req.channel,
        device: req.device,
        architecture: req.architecture,
        vehicle_release_id: req.vehicle_release_id,
        tree_hash: th,
    }))
}

/// `GET /admin/channels` — list channel targets and their current target releases.
pub async fn list_channels(
    State(s): State<AppState>,
) -> Result<Json<Vec<ChannelTargetState>>, AppError> {
    let pool = s.pool()?;
    let rows = sqlx::query(
        "SELECT ct.channel, ct.device, ct.architecture, ct.tree_hash, \
                v.config_snapshot, v.id, v.tag, v.version, \
                v.created_at::text AS created_at \
         FROM channel_targets ct JOIN vehicle_releases v ON v.id = ct.vehicle_release_id \
         ORDER BY ct.channel, ct.device, ct.architecture",
    )
    .fetch_all(pool)
    .await
    .map_err(db)?;

    let targets = rows
        .into_iter()
        .map(|r| {
            let target_release = VehicleRef {
                id: r.get("id"),
                tag: r.get("tag"),
                version: r.get("version"),
                created_at: r.get("created_at"),
            };
            ChannelTargetState {
                channel: r.get("channel"),
                device: Some(r.get("device")),
                architecture: Some(r.get("architecture")),
                vehicle: Some(target_release.clone()),
                target_release: Some(target_release),
                tree_hash: Some(r.get("tree_hash")),
                config_snapshot: r.get("config_snapshot"),
            }
        })
        .collect();

    Ok(Json(targets))
}

/// `GET /admin/channel-targets?channel=&target_type=&profile=` — the resolved
/// target's current vehicle release (the build-number source for a reconcile) +
/// its tree hash. `target_type`/`profile` are optional (default: the channel's
/// single target). A null `vehicle` means the target is unset/unknown.
pub async fn get_channel_target(
    State(s): State<AppState>,
    Query(sel): Query<TargetSelector>,
) -> Result<Json<ChannelTargetState>, AppError> {
    let pool = s.pool()?;
    let channel = sel
        .channel
        .ok_or_else(|| AppError::BadRequest("channel is required".into()))?;
    let row = sqlx::query(
        "SELECT ct.device, ct.architecture, v.config_snapshot, v.id, v.tag, v.version, \
                v.created_at::text AS created_at, ct.tree_hash \
         FROM channel_targets ct JOIN vehicle_releases v ON v.id = ct.vehicle_release_id \
         WHERE ct.channel = $1 \
           AND ($2::text IS NULL OR ct.device = $2) \
           AND ($3::text IS NULL OR ct.architecture = $3) \
         ORDER BY ct.updated_at DESC LIMIT 1",
    )
    .bind(&channel)
    .bind(&sel.device)
    .bind(&sel.architecture)
    .fetch_optional(pool)
    .await
    .map_err(db)?;

    let (device, architecture, target_release, tree_hash, config_snapshot) = match row {
        Some(r) => (
            Some(r.get("device")),
            Some(r.get("architecture")),
            Some(VehicleRef {
                id: r.get("id"),
                tag: r.get("tag"),
                version: r.get("version"),
                created_at: r.get("created_at"),
            }),
            Some(r.get::<String, _>("tree_hash")),
            r.get("config_snapshot"),
        ),
        None => (None, None, None, None, None),
    };
    Ok(Json(ChannelTargetState {
        channel,
        device,
        architecture,
        vehicle: target_release.clone(),
        target_release,
        tree_hash,
        config_snapshot,
    }))
}

/// `GET /channel-targets/tree?channel=&target_type=&profile=` — resolve a target
/// to its desired tree. `target_type`/`profile` optional (default: the channel's
/// single target).
pub async fn channel_target_tree(
    State(s): State<AppState>,
    Query(sel): Query<TargetSelector>,
) -> Result<Json<Tree>, AppError> {
    let tree = resolve_target(s.pool()?, &sel)
        .await?
        .ok_or(AppError::NotFound)?;
    Ok(Json(tree))
}

/// `POST /channel-targets/l1` body — "vehicle state in → signed L1 out".
#[derive(Deserialize)]
pub struct L1Request {
    #[serde(default)]
    pub channel: Option<String>,
    #[serde(default)]
    pub vehicle_release_id: Option<i64>,
    #[serde(default)]
    pub tree_hash: Option<String>,
    pub device: String,
    pub architecture: String,
    /// Device public key as hex of its COSE_Key CBOR (relayed from Tower 1's
    /// roster — the orchestrator hands identity, never a secret).
    pub device_pubkey: String,
    /// Device id — the recipient `kid` for the per-device CEK re-wrap.
    pub device_id: String,
    /// The vehicle's self-reported current state — the orchestrator serializes its
    /// observed [`wire::Tree`] here. The tower uses it to OMIT components the
    /// vehicle already carries (matched by plaintext content digest) so it neither
    /// builds their L2 nor re-wraps their CEK: the L1 then carries only components
    /// that differ or are unknown to the vehicle. Absent (`None`) ⇒ nothing is
    /// skipped and the full target is built (the tower stays authoritative).
    #[serde(default)]
    pub current_state: Option<Value>,
    /// SUIT sequence number (anti-replay) for the L1 and its L2s.
    #[serde(default = "default_l1_seq")]
    pub seq: u64,
}

fn default_l1_seq() -> u64 {
    1
}

/// `POST /channel-targets/l1` — the "state in → signed L1 out" call.
///
/// Resolves the channel to its full desired [`wire::Tree`] and returns a
/// per-device, sw-authority-signed **L1 campaign**: one embedded L2 image per
/// component, each with the content key re-wrapped to `device_pubkey`. Firmware
/// ciphertext stays content-addressed in the blob store — the L1 carries only
/// manifests, never firmware bytes — so the orchestrator relays this opaque,
/// signed artifact and streams ciphertext from the blob store with no device
/// private key.
///
/// When the request carries the vehicle's `current_state`, components it already
/// holds (matched by plaintext content digest) are omitted, so the L1 carries only
/// what differs or is unknown; the vehicle reconciles each against its own banks.
/// Without a `current_state` the full authoritative target is built (every
/// component, even ones already installed) — the pre-skip behavior.
pub async fn channel_target_l1(
    State(s): State<AppState>,
    Json(mut req): Json<L1Request>,
) -> Result<Response, AppError> {
    let device_pubkey = hex::decode(req.device_pubkey.trim())
        .map_err(|_| AppError::BadRequest("device_pubkey must be hex".into()))?;
    CoseKey::from_cose_key_bytes(&device_pubkey)
        .map_err(|_| AppError::BadRequest("device_pubkey is not a valid COSE_Key".into()))?;

    // The vehicle's self-report (the orchestrator's serialized observed tree) lets
    // us omit components it already carries. Parse leniently: an unparseable report
    // means we skip nothing and build the full target — never skip on uncertainty.
    let reported_state: Option<Tree> = match req.current_state.take() {
        None => None,
        Some(value) => match serde_json::from_value::<Tree>(value) {
            Ok(state) => Some(state),
            Err(e) => {
                tracing::warn!(
                    target = %target_label(&req.channel, req.vehicle_release_id),
                    device = %req.device,
                    error = %e,
                    "L1 request carried an unparseable vehicle-state report; \
                     building the full target"
                );
                None
            }
        },
    };

    let selector = TargetSelector {
        channel: req.channel.clone(),
        device: Some(req.device.clone()),
        architecture: Some(req.architecture.clone()),
        vehicle_release_id: req.vehicle_release_id,
        tree_hash: req.tree_hash.clone(),
    };
    if let Some(id) = req.vehicle_release_id {
        let matches = release_matches_target(s.pool()?, id, &req.device, &req.architecture)
            .await
            .map_err(db)?;
        if !matches {
            return Err(AppError::NotFound);
        }
    }
    let tree = resolve_target(s.pool()?, &selector)
        .await?
        .ok_or(AppError::NotFound)?;

    // Split the target's components into those to build, those disabled (a signed
    // disable manifest, not a flash), and those the vehicle already carries
    // (omitted from the L1 — no L2 build, no CEK re-wrap).
    let (included, disabled, skipped) = partition_l1_components(&tree, reported_state.as_ref());
    for path in &skipped {
        tracing::info!(
            target = %target_label(&req.channel, req.vehicle_release_id),
            device = %req.device,
            component = %path,
            "L1 skip: desired administrative/content state requires no update"
        );
    }

    // One per-device L2 per included component, plus a signed disable manifest per
    // disabled member; wrap them all into the L1. A disabled member is deactivated,
    // not flashed — its `build_disable_envelope` output is the same `Vec<u8>` shape
    // `build_campaign` embeds, so the campaign ships it like any other L2.
    let mut l2s: Vec<(String, Vec<u8>)> = Vec::with_capacity(included.len() + disabled.len());
    for (path, entity) in included.into_iter().chain(disabled) {
        let l2 = if entity.disabled {
            tracing::info!(
                target = %target_label(&req.channel, req.vehicle_release_id),
                device = %req.device,
                component = %path,
                "L1 disable: emitting a signed disable manifest for this component"
            );
            s.signer
                .build_disable_envelope(path, req.seq)
                .map_err(|e| {
                    AppError::Internal(anyhow::anyhow!("L2 disable build failed for {path}: {e}"))
                })?
        } else {
            tracing::info!(
                target = %target_label(&req.channel, req.vehicle_release_id),
                device = %req.device,
                component = %path,
                "L1 include: building component into the campaign"
            );
            let mut parts = Vec::with_capacity(entity.parts.len());
            for p in &entity.parts {
                let entry = s.index.get(&p.content).await?.ok_or(AppError::NotFound)?;
                parts.push(EnvelopePart {
                    id: p.id.clone(),
                    inner: *p.content.as_bytes(),
                    size: entry.size,
                    cek: entry.cek,
                    iv: entry.nonce,
                    outer: Some(entry.outer),
                });
            }
            s.signer
                .build_envelope(
                    &device_pubkey,
                    req.device_id.as_bytes(),
                    path,
                    &parts,
                    req.seq,
                )
                .map_err(|e| {
                    AppError::Internal(anyhow::anyhow!("L2 build failed for {path}: {e}"))
                })?
        };
        l2s.push((path.clone(), l2));
    }
    // Empty ⇒ nothing to ship. Two distinct reasons, distinct signals — because
    // `CampaignBuilder` cannot encode a zero-dependency campaign (it errors by
    // design), so an empty L1 has no CBOR body to return:
    //   * every component agreed (`skipped` non-empty) ⇒ the vehicle is already at
    //     target. A clean NO-OP, not an error: 204 No Content, which the
    //     orchestrator treats as "nothing to flash" (an empty campaign).
    //   * no shippable parts at all (`skipped` empty) ⇒ a genuinely empty target,
    //     the same 404 this handler already returned.
    if l2s.is_empty() {
        if !skipped.is_empty() {
            return Ok(StatusCode::NO_CONTENT.into_response());
        }
        return Err(AppError::NotFound);
    }

    let l1 = s
        .signer
        .build_campaign(&l2s, req.seq)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("L1 build failed: {e}")))?;
    Ok(([(header::CONTENT_TYPE, "application/cbor")], l1).into_response())
}

/// Whether the vehicle's self-reported `reported` state already carries this
/// resolved entity — so the tower can OMIT it from the L1. AGREED iff the report
/// has an entity at the same `path` AND every one of the resolved entity's parts
/// has its plaintext `content` digest present among that reported entity's parts.
///
/// Matched by digest value, never by part name: the vehicle reports files under
/// their on-disk bank filenames (a layout remap of the part id), so a name join
/// would silently never fire — equal digest ⇔ equal content. An entity absent from
/// the report, or any resolved part whose digest the vehicle lacks, is NOT agreed
/// (include it — the safe default; never skip on uncertainty). This mirrors the
/// orchestrator's `component_unchanged` push-diff: the tower's `content` and the
/// vehicle's reported `content` are the same currency (32-byte plaintext SHA-256).
///
/// Called only for entities that have parts (see [`partition_l1_components`]), so
/// the `all` is never vacuously true here.
fn entity_agreed(reported: &Tree, path: &str, resolved: &Entity) -> bool {
    let Some(rep) = reported.entities.get(path) else {
        return false;
    };
    resolved
        .parts
        .iter()
        .all(|p| rep.parts.iter().any(|rp| rp.content == p.content))
}

fn target_label(channel: &Option<String>, vehicle_release_id: Option<i64>) -> String {
    vehicle_release_id
        .map(|id| format!("vehicle release {id}"))
        .or_else(|| channel.clone())
        .unwrap_or_else(|| "unspecified target".into())
}

/// A resolved component for L1 assembly: its tree path and entity. The pair
/// [`partition_l1_components`] hands the build loop to turn into a flash envelope
/// or a disable manifest.
type ComponentEntry<'a> = (&'a String, &'a Entity);

/// Partition a resolved target tree's components for L1 assembly against the
/// vehicle's self-reported `reported` state: `(included, disabled, skipped)`.
///
/// A component goes to `disabled` only when desired is disabled and the vehicle
/// explicitly reports it enabled. Already-disabled components are skipped; absent
/// administrative state is unknown/non-disableable and is not sent a disable.
/// Otherwise a component is SKIPPED
/// (omitted from the L1 — no L2 build, no CEK re-wrap) when the vehicle already
/// carries it ([`entity_agreed`]); else it is INCLUDED and built as the
/// authoritative target. Enabled entities with no parts are in none of the sets
/// (they carry nothing to ship). `reported` `None` ⇒ enabled components are built
/// in full, while desired disables are not sent to an unknown/non-disableable target.
fn partition_l1_components<'a>(
    tree: &'a Tree,
    reported: Option<&Tree>,
) -> (
    Vec<ComponentEntry<'a>>,
    Vec<ComponentEntry<'a>>,
    Vec<&'a String>,
) {
    let mut included = Vec::new();
    let mut disabled = Vec::new();
    let mut skipped = Vec::new();
    for (path, entity) in &tree.entities {
        let observed_admin = reported
            .and_then(|rep| rep.entities.get(path))
            .and_then(|entity| entity.admin_disabled);
        if entity.disabled {
            if observed_admin == Some(false) {
                disabled.push((path, entity));
            } else {
                skipped.push(path);
            }
            continue;
        }
        if entity.parts.is_empty() {
            continue;
        }
        match reported {
            Some(rep) if observed_admin != Some(true) && entity_agreed(rep, path, entity) => {
                skipped.push(path)
            }
            _ => included.push((path, entity)),
        }
    }
    (included, disabled, skipped)
}

/// `GET /admin/artifacts/{inner}` — does Tower 2 already have this content?
/// `200` + the ref if stored, `404` if not — so a build step can skip the upload.
pub async fn artifact_exists(
    State(s): State<AppState>,
    Path(inner): Path<String>,
) -> Result<Json<ArtifactRef>, AppError> {
    let inner: ContentHash = inner.parse().map_err(|_| AppError::BadHash)?;
    match s.index.get(&inner).await? {
        Some(e) => Ok(Json(ArtifactRef {
            inner: e.inner,
            outer: e.outer,
            size: e.size,
        })),
        None => Err(AppError::NotFound),
    }
}

// --- identity --------------------------------------------------------------

/// A component release's content identity: a hash over its entity kind and its
/// parts (sorted by id, so order doesn't matter). Two releases with the same
/// identity have byte-identical content.
fn component_identity(entity_kind: &str, parts: &[NewPart]) -> String {
    let mut sorted: Vec<&NewPart> = parts.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));

    let mut buf = String::new();
    buf.push_str(entity_kind);
    buf.push('\n');
    for p in sorted {
        buf.push_str(&p.id);
        buf.push('\0');
        buf.push_str(&p.kind);
        buf.push('\0');
        buf.push_str(&p.content.to_prefixed());
        buf.push('\n');
    }
    ContentHash::of(buf.as_bytes()).to_prefixed()
}

/// A vehicle release's content identity: a hash over its (sorted, deduped)
/// member component-release ids, plus the subset of those members marked
/// **disabled**. Member ids are themselves content-deduped, so the same
/// whole-vehicle content yields the same identity.
///
/// A disabled member is a distinct whole-vehicle state (the member is deactivated,
/// not flashed), so it MUST fold into the identity — otherwise a disable would
/// reuse (silently no-op against) the enabled release. An enabled-only release
/// (no disabled members) hashes exactly as before, so existing releases still
/// dedup; a disabled id that isn't a member has no stored effect and so does not
/// perturb the identity (kept consistent with the resolved [`tree_hash`]).
fn vehicle_identity(members: &[i64], disabled_members: &[i64]) -> String {
    let mut sorted = members.to_vec();
    sorted.sort_unstable();
    sorted.dedup();
    let mut buf = sorted
        .iter()
        .map(|m| m.to_string())
        .collect::<Vec<_>>()
        .join(",");

    let mut disabled: Vec<i64> = disabled_members
        .iter()
        .copied()
        .filter(|d| sorted.binary_search(d).is_ok())
        .collect();
    disabled.sort_unstable();
    disabled.dedup();
    if !disabled.is_empty() {
        buf.push_str("\ndisabled:");
        buf.push_str(
            &disabled
                .iter()
                .map(|m| m.to_string())
                .collect::<Vec<_>>()
                .join(","),
        );
    }
    ContentHash::of(buf.as_bytes()).to_prefixed()
}

// --- resolution ------------------------------------------------------------

/// Resolve a (channel, device?, architecture?) to its desired [`wire::Tree`].
/// `None` when the target is unknown (or, without an explicit device/arch, the
/// channel has zero or several targets — the caller then asks for a selector).
async fn resolve_channel_target(
    pool: &PgPool,
    channel: &str,
    device: Option<&str>,
    architecture: Option<&str>,
) -> sqlx::Result<Option<Tree>> {
    let Some(vehicle_id) = channel_target_vehicle(pool, channel, device, architecture).await?
    else {
        return Ok(None);
    };
    Ok(Some(resolve_members_to_tree(pool, vehicle_id).await?))
}

/// Resolve either an immutable vehicle release or the existing mutable channel
/// selector. A supplied tree hash binds the request to the expected release tree.
async fn resolve_target(
    pool: &PgPool,
    selector: &TargetSelector,
) -> Result<Option<Tree>, AppError> {
    let tree = if let Some(id) = selector.vehicle_release_id {
        let exists: bool =
            sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM vehicle_releases WHERE id = $1)")
                .bind(id)
                .fetch_one(pool)
                .await
                .map_err(db)?;
        if !exists {
            return Ok(None);
        }
        Some(resolve_members_to_tree(pool, id).await.map_err(db)?)
    } else if let Some(channel) = selector.channel.as_deref() {
        resolve_channel_target(
            pool,
            channel,
            selector.device.as_deref(),
            selector.architecture.as_deref(),
        )
        .await
        .map_err(db)?
    } else {
        return Err(AppError::BadRequest(
            "channel or vehicle_release_id is required".into(),
        ));
    };
    if let (Some(expected), Some(tree)) = (selector.tree_hash.as_deref(), tree.as_ref()) {
        if tree_hash(tree) != expected {
            return Err(AppError::BadRequest(
                "tree_hash does not match release".into(),
            ));
        }
    }
    Ok(tree)
}

/// The vehicle release id a (channel, device?, architecture?) points at. With an
/// explicit device+architecture it's an exact lookup; without, it resolves a
/// channel that has exactly one target (zero or many -> `None`).
async fn channel_target_vehicle(
    pool: &PgPool,
    channel: &str,
    device: Option<&str>,
    architecture: Option<&str>,
) -> sqlx::Result<Option<i64>> {
    if let (Some(d), Some(a)) = (device, architecture) {
        let row = sqlx::query(
            "SELECT vehicle_release_id FROM channel_targets \
             WHERE channel = $1 AND device = $2 AND architecture = $3",
        )
        .bind(channel)
        .bind(d)
        .bind(a)
        .fetch_optional(pool)
        .await?;
        return Ok(row.map(|r| r.get("vehicle_release_id")));
    }
    let rows = sqlx::query("SELECT vehicle_release_id FROM channel_targets WHERE channel = $1")
        .bind(channel)
        .fetch_all(pool)
        .await?;
    Ok(if rows.len() == 1 {
        Some(rows[0].get("vehicle_release_id"))
    } else {
        None
    })
}

async fn release_matches_target(
    pool: &PgPool,
    vehicle_release_id: i64,
    device: &str,
    architecture: &str,
) -> sqlx::Result<bool> {
    sqlx::query_scalar(
        "SELECT EXISTS(SELECT 1 FROM vehicle_release_targets \
         WHERE vehicle_release_id = $1 AND device = $2 AND architecture = $3)",
    )
    .bind(vehicle_release_id)
    .bind(device)
    .bind(architecture)
    .fetch_one(pool)
    .await
}

/// A vehicle release id -> its desired [`wire::Tree`] (member component releases
/// -> their entities + parts).
async fn resolve_members_to_tree(pool: &PgPool, vehicle_id: i64) -> sqlx::Result<Tree> {
    let members = sqlx::query(
        "SELECT component_release_id, disabled FROM vehicle_release_members WHERE vehicle_release_id = $1",
    )
    .bind(vehicle_id)
    .fetch_all(pool)
    .await?;

    let mut tree = Tree::default();
    for m in members {
        let rid: i64 = m.get("component_release_id");
        let disabled: bool = m.get("disabled");
        let row = sqlx::query(
            "SELECT entity_path, entity_kind, version FROM component_releases WHERE id = $1",
        )
        .bind(rid)
        .fetch_one(pool)
        .await?;
        let path: String = row.get("entity_path");
        let mut entity = Entity {
            kind: row.get("entity_kind"),
            version: Some(row.get("version")),
            update_mode: None,
            parts: Vec::new(),
            disabled,
            admin_disabled: None,
        };
        let parts =
            sqlx::query("SELECT part_id, part_kind, content_hash FROM component_release_parts WHERE release_id = $1")
                .bind(rid)
                .fetch_all(pool)
                .await?;
        for p in parts {
            let part_id: String = p.get("part_id");
            let content_hash: String = p.get("content_hash");
            let content = parse_stored_hash(&content_hash, vehicle_id, rid, &path, &part_id)?;
            entity.parts.push(Part {
                kind: p.get("part_kind"),
                id: part_id,
                content,
            });
        }
        tree.entities.insert(path, entity);
    }
    Ok(tree)
}

/// Parse a content hash read from a release row into a [`ContentHash`], failing
/// loudly when it doesn't parse. A stored release is authoritative *desired*
/// state, so a malformed hash is corruption — it fails the whole tree resolution
/// (surfaced as a 500 by `db` → `AppError::Internal`) rather than silently dropping
/// the part into invisible drift. The message names the release, component and part
/// plus the offending string so the corrupt row is findable.
fn parse_stored_hash(
    content_hash: &str,
    vehicle_release_id: i64,
    component_release_id: i64,
    entity_path: &str,
    part_id: &str,
) -> sqlx::Result<ContentHash> {
    content_hash.parse::<ContentHash>().map_err(|_| {
        sqlx::Error::Protocol(format!(
            "vehicle release {vehicle_release_id}, component release \
             {component_release_id} ({entity_path}), part '{part_id}': malformed \
             content hash '{content_hash}'"
        ))
    })
}

/// Content-stable canonical hash of a resolved tree: entity paths in order (the
/// [`Tree`] map is already sorted), each with its parts sorted by id. Binds
/// plan -> execute (multi-profile spec §2.2) — unlike a vehicle release's
/// id-based identity hash, it is identical across DB instances for the same
/// content.
fn tree_hash(tree: &Tree) -> String {
    let mut buf = String::new();
    for (path, entity) in &tree.entities {
        buf.push_str(path);
        buf.push('\n');
        // A disabled member is a distinct desired state (deactivated, not flashed),
        // so it MUST change the tree hash; an enabled entity is byte-identical to
        // before (additive).
        if entity.disabled {
            buf.push_str("disabled\n");
        }
        let mut parts: Vec<&Part> = entity.parts.iter().collect();
        parts.sort_by(|a, b| a.id.cmp(&b.id));
        for p in parts {
            buf.push_str(&p.id);
            buf.push('\0');
            buf.push_str(&p.content.to_prefixed());
            buf.push('\n');
        }
    }
    ContentHash::of(buf.as_bytes()).to_prefixed()
}

/// Map a database error into an `AppError`.
fn db(e: sqlx::Error) -> AppError {
    AppError::Internal(e.into())
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use axum::routing::{get, post, put};
    use axum::Router;
    use tower::ServiceExt;

    use crate::content::AppState;
    use crate::signer::Signer;
    use crate::store::{FsBlobStore, PgIndex};
    use sumo_codec::commands::CommandValue;
    use sumo_codec::labels::SUIT_DIRECTIVE_DISABLE;
    use sumo_crypto::RustCryptoBackend;
    use sumo_offboard::keygen;
    use sumo_onboard::validator::Validator;

    fn part(id: &str, kind: &str, content: &str) -> NewPart {
        NewPart {
            id: id.into(),
            kind: kind.into(),
            content: ContentHash::of(content.as_bytes()),
        }
    }

    // --- tower-side skip (current_state → omit already-carried components) ------

    fn wpart(id: &str, content: &[u8]) -> Part {
        Part {
            kind: "file".into(),
            id: id.into(),
            content: ContentHash::of(content),
        }
    }

    fn wentity(parts: Vec<Part>) -> Entity {
        Entity {
            kind: "vm".into(),
            version: None,
            update_mode: None,
            parts,
            disabled: false,
            admin_disabled: None,
        }
    }

    fn wtree(entries: Vec<(&str, Entity)>) -> Tree {
        Tree {
            entities: entries
                .into_iter()
                .map(|(k, v)| (k.to_string(), v))
                .collect(),
        }
    }

    #[test]
    fn entity_agreed_matches_by_digest_ignoring_part_name() {
        // The tower names parts kernel/rootfs; the vehicle reports the SAME content
        // under remapped on-disk filenames — agreement must still fire (digest join).
        let resolved = wentity(vec![wpart("kernel", b"K"), wpart("rootfs", b"R")]);
        let reported = wtree(vec![(
            "vm1",
            wentity(vec![wpart("boot.img", b"K"), wpart("rootfs.img", b"R")]),
        )]);
        assert!(entity_agreed(&reported, "vm1", &resolved));
    }

    #[test]
    fn entity_agreed_false_when_entity_absent_or_part_missing() {
        let resolved = wentity(vec![wpart("kernel", b"K2"), wpart("rootfs", b"R")]);
        // Vehicle reports nothing for vm1 → not agreed (absent).
        assert!(!entity_agreed(&Tree::default(), "vm1", &resolved));
        // Vehicle has rootfs R but only the OLD kernel K1 — the K2 digest is absent.
        let stale = wtree(vec![(
            "vm1",
            wentity(vec![wpart("boot.img", b"K1"), wpart("rootfs.img", b"R")]),
        )]);
        assert!(!entity_agreed(&stale, "vm1", &resolved));
    }

    #[test]
    fn partition_skips_agreed_includes_rest_and_ignores_partless() {
        let tree = wtree(vec![
            (
                "vm1",
                wentity(vec![wpart("kernel", b"K"), wpart("rootfs", b"R")]),
            ),
            ("vm2", wentity(vec![wpart("kernel", b"K2")])),
            ("empty", wentity(vec![])),
        ]);
        // Vehicle carries vm1's content (remapped names) but not vm2.
        let reported = wtree(vec![(
            "vm1",
            wentity(vec![wpart("boot.img", b"K"), wpart("rootfs.img", b"R")]),
        )]);

        let (included, disabled, skipped) = partition_l1_components(&tree, Some(&reported));
        let inc: Vec<&str> = included.iter().map(|(p, _)| p.as_str()).collect();
        let skp: Vec<&str> = skipped.iter().map(|p| p.as_str()).collect();
        assert_eq!(inc, vec!["vm2"], "only the changed component is built");
        assert_eq!(skp, vec!["vm1"], "the already-carried component is skipped");
        assert!(disabled.is_empty(), "no members disabled in this tree");

        // None ⇒ every entity WITH parts is included, nothing skipped (the partless
        // entity is excluded either way — it carries nothing to ship).
        let (included, disabled, skipped) = partition_l1_components(&tree, None);
        let inc: Vec<&str> = included.iter().map(|(p, _)| p.as_str()).collect();
        assert_eq!(inc, vec!["vm1", "vm2"]);
        assert!(skipped.is_empty());
        assert!(disabled.is_empty());
    }

    /// Every component agreed ⇒ nothing included, everything skipped — the "vehicle
    /// already at target" case the handler turns into a 204 no-op (an empty L1 has
    /// no `CampaignBuilder` encoding, so it can't be a signed body).
    #[test]
    fn partition_all_agreed_includes_nothing() {
        let tree = wtree(vec![
            ("vm1", wentity(vec![wpart("kernel", b"K")])),
            ("vm2", wentity(vec![wpart("kernel", b"K2")])),
        ]);
        // Vehicle carries both (remapped on-disk names, same content digests).
        let reported = wtree(vec![
            ("vm1", wentity(vec![wpart("boot.img", b"K")])),
            ("vm2", wentity(vec![wpart("boot.img", b"K2")])),
        ]);
        let (included, disabled, skipped) = partition_l1_components(&tree, Some(&reported));
        assert!(included.is_empty(), "nothing to build — vehicle at target");
        assert!(disabled.is_empty(), "no members disabled in this tree");
        let skp: Vec<&str> = skipped.iter().map(|p| p.as_str()).collect();
        assert_eq!(skp, vec!["vm1", "vm2"], "every component skipped");
    }

    #[test]
    fn partition_includes_disabled_vehicle_component_to_enable_it() {
        let tree = wtree(vec![("vm1", wentity(vec![wpart("kernel", b"K")]))]);
        let mut observed = wentity(vec![wpart("boot.img", b"K")]);
        observed.admin_disabled = Some(true);
        let reported = wtree(vec![("vm1", observed)]);

        let (included, disabled, skipped) = partition_l1_components(&tree, Some(&reported));
        assert_eq!(included[0].0, "vm1");
        assert!(disabled.is_empty());
        assert!(skipped.is_empty());
    }

    #[test]
    fn partition_skips_when_desired_and_observed_are_disabled() {
        let mut desired = wentity(vec![wpart("kernel", b"K")]);
        desired.disabled = true;
        let tree = wtree(vec![("vm1", desired)]);
        let mut observed = wentity(vec![wpart("boot.img", b"K")]);
        observed.admin_disabled = Some(true);
        let reported = wtree(vec![("vm1", observed)]);

        let (included, disabled, skipped) = partition_l1_components(&tree, Some(&reported));
        assert!(included.is_empty());
        assert!(disabled.is_empty());
        assert_eq!(
            skipped.iter().map(|p| p.as_str()).collect::<Vec<_>>(),
            vec!["vm1"]
        );
    }

    /// Build a signed L1 over `included` + `disabled` (fake CEK/IV/outer — no blob
    /// store in a unit test) exactly as the handler does: included components get a
    /// flash envelope, disabled members get a `build_disable_envelope` manifest.
    /// Returns the validated campaign manifest so a test can assert which components
    /// it carries. Reuses the signer + `Validator` path the signer tests use.
    fn build_l1(
        signer: &Signer,
        device_pubkey: &[u8],
        included: &[(&String, &Entity)],
        disabled: &[(&String, &Entity)],
    ) -> sumo_onboard::Manifest {
        let mut l2s: Vec<(String, Vec<u8>)> = Vec::new();
        for &(path, entity) in included.iter().chain(disabled) {
            let l2 = if entity.disabled {
                signer.build_disable_envelope(path, 1).unwrap()
            } else {
                let parts: Vec<EnvelopePart> = entity
                    .parts
                    .iter()
                    .map(|p| EnvelopePart {
                        id: p.id.clone(),
                        inner: *p.content.as_bytes(),
                        size: 42,
                        cek: [7u8; 16],
                        iv: [9u8; 12],
                        outer: Some(ContentHash::of(p.id.as_bytes())),
                    })
                    .collect();
                signer
                    .build_envelope(device_pubkey, b"dev-1", path, &parts, 1)
                    .unwrap()
            };
            l2s.push((path.clone(), l2));
        }
        let l1 = signer.build_campaign(&l2s, 3).expect("L1 builds");
        // The campaign keys each embedded L2 as `#<component>`; validating against
        // the sw-authority anchor returns the decoded manifest we inspect.
        Validator::new(&signer.public_key_cbor(), None)
            .validate_envelope(&l1, &RustCryptoBackend::new(), 0)
            .expect("L1 validates against the sw-authority anchor")
    }

    #[test]
    fn built_l1_omits_agreed_and_keeps_changed() {
        let signer = Signer::generate().unwrap();
        let device = keygen::generate_device_key(keygen::ES256).unwrap();
        let pubkey = device.public_key_bytes();

        let tree = wtree(vec![
            ("vm1", wentity(vec![wpart("kernel", b"K")])),
            ("vm2", wentity(vec![wpart("kernel", b"K2")])),
        ]);
        // Vehicle already carries vm1 (remapped name); vm2 is new/changed.
        let reported = wtree(vec![("vm1", wentity(vec![wpart("boot.img", b"K")]))]);

        let (included, disabled, _) = partition_l1_components(&tree, Some(&reported));
        let m = build_l1(&signer, &pubkey, &included, &disabled);
        assert!(
            m.integrated_payload("#vm2").is_some(),
            "changed component must be present in the L1"
        );
        assert!(
            m.integrated_payload("#vm1").is_none(),
            "agreed component must be omitted from the L1"
        );
    }

    #[test]
    fn built_l1_without_state_includes_all_components() {
        let signer = Signer::generate().unwrap();
        let device = keygen::generate_device_key(keygen::ES256).unwrap();
        let pubkey = device.public_key_bytes();

        let tree = wtree(vec![
            ("vm1", wentity(vec![wpart("kernel", b"K")])),
            ("vm2", wentity(vec![wpart("kernel", b"K2")])),
        ]);
        // None current_state ⇒ no skip: both components are built into the L1.
        let (included, disabled, skipped) = partition_l1_components(&tree, None);
        assert!(skipped.is_empty());
        let m = build_l1(&signer, &pubkey, &included, &disabled);
        assert!(m.integrated_payload("#vm1").is_some());
        assert!(m.integrated_payload("#vm2").is_some());
    }

    /// A release with a member DISABLED assembles an L1 where that component's L2 is
    /// a `build_disable_envelope` output (no firmware, carries the
    /// `suit-directive-disable`), while an enabled member is still flashed with a
    /// normal envelope (carries firmware). Mirrors the handler's build loop.
    #[test]
    fn built_l1_disables_disabled_member_and_flashes_enabled() {
        let signer = Signer::generate().unwrap();
        let device = keygen::generate_device_key(keygen::ES256).unwrap();
        let pubkey = device.public_key_bytes();

        // vm1 enabled (flash), vm2 disabled (deactivate).
        let mut vm2 = wentity(vec![wpart("kernel", b"K2")]);
        vm2.disabled = true;
        let tree = wtree(vec![
            ("vm1", wentity(vec![wpart("kernel", b"K")])),
            ("vm2", vm2),
        ]);

        // The vehicle explicitly reports vm2 enabled, so desired disabled differs.
        let mut observed_vm2 = wentity(vec![wpart("boot.img", b"K2")]);
        observed_vm2.admin_disabled = Some(false);
        let reported = wtree(vec![("vm2", observed_vm2)]);
        let (included, disabled, skipped) = partition_l1_components(&tree, Some(&reported));
        let inc: Vec<&str> = included.iter().map(|(p, _)| p.as_str()).collect();
        let dis: Vec<&str> = disabled.iter().map(|(p, _)| p.as_str()).collect();
        assert_eq!(inc, vec!["vm1"], "the enabled member is flashed");
        assert_eq!(dis, vec!["vm2"], "the disabled member is routed to disable");
        assert!(skipped.is_empty());

        let l1 = build_l1(&signer, &pubkey, &included, &disabled);
        let crypto = RustCryptoBackend::new();

        // vm1: an ordinary flash envelope — carries a firmware payload.
        let vm1_l2 = l1
            .integrated_payload("#vm1")
            .expect("enabled member present in the L1");
        let vm1_m = Validator::new(&signer.public_key_cbor(), None)
            .validate_envelope(vm1_l2, &crypto, 0)
            .expect("enabled L2 validates");
        assert!(
            vm1_m.has_firmware(),
            "the enabled member is flashed (carries firmware)"
        );

        // vm2: a disable manifest — no firmware, carries suit-directive-disable.
        let vm2_l2 = l1
            .integrated_payload("#vm2")
            .expect("disabled member present in the L1");
        let vm2_m = Validator::new(&signer.public_key_cbor(), None)
            .validate_envelope(vm2_l2, &crypto, 0)
            .expect("disable L2 validates");
        assert!(
            !vm2_m.has_firmware(),
            "the disabled member carries no firmware"
        );
        let disable = vm2_m
            .envelope()
            .manifest
            .common
            .shared_sequence
            .items
            .iter()
            .find(|c| c.label == SUIT_DIRECTIVE_DISABLE)
            .expect("disable directive present");
        assert!(matches!(disable.value, CommandValue::Disable));
    }

    /// THE critical invariant: a disable is a NEW immutable, content-addressed
    /// release. A member marked disabled MUST change BOTH the vehicle identity and
    /// the resolved tree hash vs. the same release with it enabled — otherwise the
    /// disable reuses (silently no-ops against) the enabled release. Enabled-only
    /// inputs are unchanged (additive), and a disabled id that isn't a member has no
    /// effect (kept consistent with the resolved tree).
    #[test]
    fn disabled_member_changes_identity_and_tree_hash() {
        // vehicle_identity: disabling a member yields a distinct identity.
        assert_ne!(
            vehicle_identity(&[1, 2, 3], &[]),
            vehicle_identity(&[1, 2, 3], &[2]),
            "a disabled member must change the vehicle identity"
        );
        // Additive: no disabled members ⇒ the pre-disable identity, and a disabled
        // id that isn't a member has no stored effect ⇒ no identity change.
        assert_eq!(
            vehicle_identity(&[1, 2, 3], &[]),
            vehicle_identity(&[1, 2, 3], &[99])
        );

        // tree_hash: the same resolved tree with a member disabled hashes
        // differently than with it enabled.
        let enabled = wtree(vec![("vm1", wentity(vec![wpart("kernel", b"K")]))]);
        let mut dis = wentity(vec![wpart("kernel", b"K")]);
        dis.disabled = true;
        let disabled = wtree(vec![("vm1", dis)]);
        assert_ne!(
            tree_hash(&enabled),
            tree_hash(&disabled),
            "a disabled member must change the tree hash"
        );
    }

    #[test]
    fn component_identity_ignores_part_order() {
        let a = vec![part("kernel", "bank", "k"), part("rootfs", "bank", "r")];
        let b = vec![part("rootfs", "bank", "r"), part("kernel", "bank", "k")];
        assert_eq!(
            component_identity("bank", &a),
            component_identity("bank", &b)
        );
    }

    #[test]
    fn component_identity_tracks_content_kind_and_partset() {
        let base = vec![part("kernel", "bank", "k1")];
        // content change
        assert_ne!(
            component_identity("bank", &base),
            component_identity("bank", &[part("kernel", "bank", "k2")])
        );
        // added part
        assert_ne!(
            component_identity("bank", &base),
            component_identity(
                "bank",
                &[part("kernel", "bank", "k1"), part("rootfs", "bank", "r")]
            )
        );
        // entity kind change
        assert_ne!(
            component_identity("bank", &base),
            component_identity("rt", &base)
        );
    }

    #[test]
    fn set_channel_target_accepts_target_release_alias() {
        let req: SetChannelTarget = serde_json::from_value(serde_json::json!({
            "channel": "bleeding",
            "device": "rig",
            "architecture": "arm64",
            "target_release_id": 42
        }))
        .unwrap();

        assert_eq!(req.channel, "bleeding");
        assert_eq!(req.device, "rig");
        assert_eq!(req.architecture, "arm64");
        assert_eq!(req.vehicle_release_id, 42);
    }

    #[test]
    fn new_vehicle_release_accepts_optional_config_snapshot() {
        let req: NewVehicleRelease = serde_json::from_value(serde_json::json!({
            "tag": "managed-cvc-rig",
            "version": "1.0.0-dev.1",
            "members": [1, 2],
            "config_snapshot": {
                "schema": "sumo-target-config/v1",
                "deployment": {"channel": "bleeding", "profile": "default"}
            }
        }))
        .unwrap();

        assert_eq!(req.tag, "managed-cvc-rig");
        assert_eq!(
            req.config_snapshot.unwrap()["schema"],
            "sumo-target-config/v1"
        );
    }

    #[ignore = "requires a PostgreSQL DATABASE_URL for sqlx::test"]
    #[sqlx::test(migrations = "./migrations")]
    async fn vehicle_release_snapshot_survives_reuse_and_channel_reads(pool: PgPool) {
        let app = test_app(pool);
        let component_id = create_component(&app).await;
        let original_snapshot = serde_json::json!({
            "schema": "sumo-target-config/v1",
            "target_type": {"name": "managed-cvc", "kind": "vehicle"},
            "deployment": {"channel": "bleeding", "profile": "default"},
            "labels": {"tower": "2"},
            "components": {
                "ecu-a": {
                    "kind": "adaptive-app",
                    "version": "1.0.0",
                    "parts": [{"id": "app", "kind": "binary", "source": "app.bin"}]
                }
            }
        });
        let replacement_snapshot = serde_json::json!({
            "schema": "sumo-target-config/v1",
            "deployment": {"channel": "bleeding", "profile": "replacement"}
        });

        let release = post_json(
            &app,
            "/admin/vehicle-releases",
            serde_json::json!({
                "tag": "managed-cvc",
                "version": "1.0.0",
                "members": [component_id],
                "config_snapshot": original_snapshot,
            }),
        )
        .await;
        assert_eq!(release["reused"], false);
        let release_id = release["id"].as_i64().unwrap();

        put_json(
            &app,
            "/admin/channel-targets",
            serde_json::json!({
                "channel": "bleeding",
                "device": "rig",
                "architecture": "arm64",
                "target_release_id": release_id
            }),
        )
        .await;

        let reused = post_json(
            &app,
            "/admin/vehicle-releases",
            serde_json::json!({
                "tag": "managed-cvc",
                "version": "2.0.0",
                "members": [component_id],
                "config_snapshot": replacement_snapshot,
            }),
        )
        .await;
        assert_eq!(reused["id"], release_id);
        assert_eq!(reused["reused"], true);

        let channel = get_json(
            &app,
            "/admin/channel-targets?channel=bleeding&device=rig&architecture=arm64",
        )
        .await;
        assert_eq!(channel["target_release"]["id"], release_id);
        assert_eq!(
            channel["config_snapshot"]["deployment"]["profile"],
            "default"
        );
        assert_eq!(channel["config_snapshot"]["labels"]["tower"], "2");

        let channels = get_json(&app, "/admin/channels").await;
        assert_eq!(channels[0]["channel"], "bleeding");
        assert_eq!(channels[0]["device"], "rig");
        assert_eq!(channels[0]["architecture"], "arm64");
        assert_eq!(channels[0]["target_release"]["id"], release_id);
        assert_eq!(
            channels[0]["config_snapshot"]["deployment"]["profile"],
            "default"
        );
    }

    #[ignore = "requires a PostgreSQL DATABASE_URL for sqlx::test"]
    #[sqlx::test(migrations = "./migrations")]
    async fn pinned_vehicle_release_is_unaffected_by_channel_movement(pool: PgPool) {
        let binding_pool = pool.clone();
        let app = test_app(pool);
        let component_id = create_component(&app).await;
        let enabled = post_json(
            &app,
            "/admin/vehicle-releases",
            serde_json::json!({"tag":"rig","version":"1","members":[component_id]}),
        )
        .await["id"]
            .as_i64()
            .unwrap();
        let disabled = post_json(
            &app,
            "/admin/vehicle-releases",
            serde_json::json!({
                "tag":"rig", "version":"2", "members":[component_id],
                "disabled_members":[component_id]
            }),
        )
        .await["id"]
            .as_i64()
            .unwrap();

        let point_channel = |release| {
            serde_json::json!({
                "channel":"bleeding", "device":"rig", "architecture":"arm64",
                "vehicle_release_id":release
            })
        };
        put_json(&app, "/admin/channel-targets", point_channel(enabled)).await;
        assert!(
            release_matches_target(&binding_pool, enabled, "rig", "arm64")
                .await
                .unwrap()
        );
        assert!(
            !release_matches_target(&binding_pool, enabled, "rig", "amd64")
                .await
                .unwrap()
        );
        let pinned_before = get_json(
            &app,
            &format!("/channel-targets/tree?vehicle_release_id={enabled}"),
        )
        .await;
        put_json(&app, "/admin/channel-targets", point_channel(disabled)).await;
        let pinned_after = get_json(
            &app,
            &format!("/channel-targets/tree?vehicle_release_id={enabled}"),
        )
        .await;
        let channel = get_json(
            &app,
            "/channel-targets/tree?channel=bleeding&device=rig&architecture=arm64",
        )
        .await;
        assert_eq!(pinned_after, pinned_before);
        assert_eq!(pinned_after["entities"]["ecu-a"]["disabled"], false);
        assert_eq!(channel["entities"]["ecu-a"]["disabled"], true);
    }

    #[test]
    fn vehicle_identity_ignores_order_and_dupes() {
        assert_eq!(
            vehicle_identity(&[1, 2, 3], &[]),
            vehicle_identity(&[3, 2, 1], &[])
        );
        assert_eq!(
            vehicle_identity(&[1, 2, 2, 3], &[]),
            vehicle_identity(&[1, 2, 3], &[])
        );
        assert_ne!(
            vehicle_identity(&[1, 2], &[]),
            vehicle_identity(&[1, 2, 3], &[])
        );
    }

    /// A stored release row is authoritative desired state: a content hash that no
    /// longer parses is corruption, not drift, so resolution fails loudly and the
    /// error names the offending part (and quotes the bad string) — never a silent
    /// drop. (Mirrors the per-part parse in `resolve_members_to_tree`.)
    #[test]
    fn parse_stored_hash_rejects_corrupt_member_naming_the_part() {
        let err = parse_stored_hash("not-a-content-hash", 7, 42, "vm1", "kernel")
            .unwrap_err()
            .to_string();
        assert!(err.contains("kernel"), "error must name the part: {err}");
        assert!(
            err.contains("not-a-content-hash"),
            "error must quote the offending hash: {err}"
        );

        // A well-formed hash still parses back to its ContentHash.
        let good = ContentHash::of(b"k").to_prefixed();
        assert_eq!(
            parse_stored_hash(&good, 7, 42, "vm1", "kernel").unwrap(),
            ContentHash::of(b"k")
        );
    }

    fn test_app(pool: PgPool) -> Router {
        let blob_dir = tempfile::tempdir().unwrap().keep();
        let signer = Signer::generate().unwrap();
        let state = AppState {
            blobs: Arc::new(FsBlobStore::new(blob_dir)),
            index: Arc::new(PgIndex::new(pool.clone())),
            pool: Some(pool),
            signer: Arc::new(signer),
        };

        Router::new()
            .route("/admin/component-releases", post(create_component_release))
            .route("/admin/vehicle-releases", post(create_vehicle_release))
            .route("/admin/channels", get(list_channels))
            .route(
                "/admin/channel-targets",
                put(set_channel_target).get(get_channel_target),
            )
            .route("/channel-targets/tree", get(channel_target_tree))
            .with_state(state)
    }

    async fn create_component(app: &Router) -> i64 {
        let response = post_json(
            app,
            "/admin/component-releases",
            serde_json::json!({
                "entity_path": "ecu-a",
                "entity_kind": "adaptive-app",
                "version": "1.0.0",
                "parts": [{
                    "id": "app",
                    "kind": "binary",
                    "content": ContentHash::of(b"app").to_prefixed(),
                }],
            }),
        )
        .await;
        response["id"].as_i64().unwrap()
    }

    async fn get_json(app: &Router, uri: &str) -> Value {
        let response = app
            .clone()
            .oneshot(Request::get(uri).body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        serde_json::from_slice(&bytes).unwrap()
    }

    async fn post_json(app: &Router, uri: &str, body: Value) -> Value {
        json_request(app, Request::post(uri), body, StatusCode::OK).await
    }

    async fn put_json(app: &Router, uri: &str, body: Value) -> Value {
        json_request(app, Request::put(uri), body, StatusCode::OK).await
    }

    async fn json_request(
        app: &Router,
        builder: axum::http::request::Builder,
        body: Value,
        status: StatusCode,
    ) -> Value {
        let response = app
            .clone()
            .oneshot(
                builder
                    .header("content-type", "application/json")
                    .body(Body::from(body.to_string()))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), status);
        let bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap()
        }
    }
}
