//! Release & channel storage (Tower 2).
//!
//! L2 **component releases** (one entity's versioned parts), L1 **vehicle
//! releases** (a tagged combination of component releases — the desired
//! whole-vehicle state), and **channel** pointers. Resolving a channel yields
//! the desired [`wire::Tree`]; the per-vehicle *campaign* to reach it is
//! generated by [`wire::flash_plan`], not stored here.

use axum::extract::{Path, State};
use axum::Json;
use serde::{Deserialize, Serialize};
use sqlx::{PgPool, Row};
use wire::{ArtifactRef, ContentHash, Entity, Part, Tree};

use crate::content::{AppError, AppState};

// --- request / response bodies ---------------------------------------------

/// `POST /admin/component-releases` body — one entity's versioned parts.
#[derive(Deserialize)]
pub struct NewComponentRelease {
    pub entity_path: String,
    pub entity_kind: String,
    pub version: String,
    pub parts: Vec<NewPart>,
}

#[derive(Deserialize)]
pub struct NewPart {
    pub id: String,
    pub kind: String,
    pub content: ContentHash,
}

/// `POST /admin/vehicle-releases` body — a tagged combination of component
/// releases (the desired whole-vehicle state).
#[derive(Deserialize)]
pub struct NewVehicleRelease {
    pub tag: String,
    pub version: String,
    pub members: Vec<i64>,
}

/// `PUT /admin/channels/{name}` body.
#[derive(Deserialize)]
pub struct SetChannel {
    pub vehicle_release_id: i64,
}

#[derive(Serialize)]
pub struct Created {
    pub id: i64,
}

// --- handlers --------------------------------------------------------------

/// `POST /admin/component-releases` — mint an L2 component release.
pub async fn create_component_release(
    State(s): State<AppState>,
    Json(req): Json<NewComponentRelease>,
) -> Result<Json<Created>, AppError> {
    let pool = s.pool()?;
    let id: i64 = sqlx::query(
        "INSERT INTO component_releases (entity_path, entity_kind, version) \
         VALUES ($1, $2, $3) RETURNING id",
    )
    .bind(&req.entity_path)
    .bind(&req.entity_kind)
    .bind(&req.version)
    .fetch_one(pool)
    .await
    .map_err(db)?
    .get("id");

    for p in &req.parts {
        sqlx::query(
            "INSERT INTO component_release_parts (release_id, part_id, part_kind, content_hash) \
             VALUES ($1, $2, $3, $4)",
        )
        .bind(id)
        .bind(&p.id)
        .bind(&p.kind)
        .bind(p.content.to_prefixed())
        .execute(pool)
        .await
        .map_err(db)?;
    }
    Ok(Json(Created { id }))
}

/// `POST /admin/vehicle-releases` — mint an L1 vehicle release (the desired
/// whole-vehicle state, a combination of component releases).
pub async fn create_vehicle_release(
    State(s): State<AppState>,
    Json(req): Json<NewVehicleRelease>,
) -> Result<Json<Created>, AppError> {
    let pool = s.pool()?;
    let id: i64 =
        sqlx::query("INSERT INTO vehicle_releases (tag, version) VALUES ($1, $2) RETURNING id")
            .bind(&req.tag)
            .bind(&req.version)
            .fetch_one(pool)
            .await
            .map_err(db)?
            .get("id");

    for m in &req.members {
        sqlx::query(
            "INSERT INTO vehicle_release_members (vehicle_release_id, component_release_id) \
             VALUES ($1, $2)",
        )
        .bind(id)
        .bind(m)
        .execute(pool)
        .await
        .map_err(db)?;
    }
    Ok(Json(Created { id }))
}

/// `PUT /admin/channels/{name}` — point a channel at a vehicle release.
pub async fn set_channel(
    State(s): State<AppState>,
    Path(name): Path<String>,
    Json(req): Json<SetChannel>,
) -> Result<(), AppError> {
    let pool = s.pool()?;
    sqlx::query(
        "INSERT INTO channels (name, vehicle_release_id, updated_at) VALUES ($1, $2, now()) \
         ON CONFLICT (name) DO UPDATE SET vehicle_release_id = $2, updated_at = now()",
    )
    .bind(&name)
    .bind(req.vehicle_release_id)
    .execute(pool)
    .await
    .map_err(db)?;
    Ok(())
}

/// `GET /channels/{name}/tree` — resolve a channel to its desired tree.
pub async fn channel_tree(
    State(s): State<AppState>,
    Path(name): Path<String>,
) -> Result<Json<Tree>, AppError> {
    let tree = resolve_channel(s.pool()?, &name)
        .await
        .map_err(db)?
        .ok_or(AppError::NotFound)?;
    Ok(Json(tree))
}

/// `GET /admin/artifacts/{inner}` — does Tower 2 already have this content?
/// `200` + the ref if stored, `404` if not — so a build step can skip the upload.
pub async fn artifact_exists(
    State(s): State<AppState>,
    Path(inner): Path<String>,
) -> Result<Json<ArtifactRef>, AppError> {
    let inner: ContentHash = inner.parse().map_err(|_| AppError::BadHash)?;
    match s.index.get(&inner).await? {
        Some(e) => Ok(Json(ArtifactRef {
            inner: e.inner,
            outer: e.outer,
            size: e.size,
        })),
        None => Err(AppError::NotFound),
    }
}

// --- resolution ------------------------------------------------------------

/// Resolve a channel to its desired [`wire::Tree`]: channel → vehicle release →
/// member component releases → their entities + parts. `None` when the channel
/// is unset or unknown.
async fn resolve_channel(pool: &PgPool, name: &str) -> sqlx::Result<Option<Tree>> {
    let Some(vehicle_id) = channel_vehicle(pool, name).await? else {
        return Ok(None);
    };
    let members = sqlx::query(
        "SELECT component_release_id FROM vehicle_release_members WHERE vehicle_release_id = $1",
    )
    .bind(vehicle_id)
    .fetch_all(pool)
    .await?;

    let mut tree = Tree::default();
    for m in members {
        let rid: i64 = m.get("component_release_id");
        let row = sqlx::query(
            "SELECT entity_path, entity_kind, version FROM component_releases WHERE id = $1",
        )
        .bind(rid)
        .fetch_one(pool)
        .await?;
        let path: String = row.get("entity_path");
        let mut entity = Entity {
            kind: row.get("entity_kind"),
            version: Some(row.get("version")),
            parts: Vec::new(),
        };
        let parts =
            sqlx::query("SELECT part_id, part_kind, content_hash FROM component_release_parts WHERE release_id = $1")
                .bind(rid)
                .fetch_all(pool)
                .await?;
        for p in parts {
            let content: String = p.get("content_hash");
            let Ok(content) = content.parse::<ContentHash>() else {
                continue;
            };
            entity.parts.push(Part {
                kind: p.get("part_kind"),
                id: p.get("part_id"),
                content,
            });
        }
        tree.entities.insert(path, entity);
    }
    Ok(Some(tree))
}

async fn channel_vehicle(pool: &PgPool, name: &str) -> sqlx::Result<Option<i64>> {
    let row = sqlx::query("SELECT vehicle_release_id FROM channels WHERE name = $1")
        .bind(name)
        .fetch_optional(pool)
        .await?;
    Ok(row.and_then(|r| r.get::<Option<i64>, _>("vehicle_release_id")))
}

/// Map a database error into an `AppError`.
fn db(e: sqlx::Error) -> AppError {
    AppError::Internal(e.into())
}
