-- Release & channel storage.
--
-- L2 = component_releases: one entity's versioned parts (e.g. "vm1" "1.1.0").
-- L1 = vehicle_releases: a tagged combination of component releases — the
--      desired whole-vehicle state that a channel points at. (The per-vehicle
--      *campaign* to reach a state is generated by wire::flash_plan, not stored.)
-- channels: a mutable pointer (e.g. "bleeding") to a vehicle release.
-- The desired wire::Tree for a channel is resolved by joining these.

CREATE TABLE IF NOT EXISTS component_releases (
    id          BIGSERIAL   PRIMARY KEY,
    entity_path TEXT        NOT NULL,
    entity_kind TEXT        NOT NULL,
    version     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entity_path, version)
);

CREATE TABLE IF NOT EXISTS component_release_parts (
    release_id   BIGINT NOT NULL REFERENCES component_releases(id) ON DELETE CASCADE,
    part_id      TEXT   NOT NULL,
    part_kind    TEXT   NOT NULL,
    content_hash TEXT   NOT NULL,
    PRIMARY KEY (release_id, part_id)
);

CREATE TABLE IF NOT EXISTS vehicle_releases (
    id         BIGSERIAL   PRIMARY KEY,
    tag        TEXT        NOT NULL,
    version    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tag, version)
);

CREATE TABLE IF NOT EXISTS vehicle_release_members (
    vehicle_release_id   BIGINT NOT NULL REFERENCES vehicle_releases(id) ON DELETE CASCADE,
    component_release_id BIGINT NOT NULL REFERENCES component_releases(id),
    PRIMARY KEY (vehicle_release_id, component_release_id)
);

CREATE TABLE IF NOT EXISTS channels (
    name               TEXT        PRIMARY KEY,
    vehicle_release_id BIGINT      REFERENCES vehicle_releases(id),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
